include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Turn warnings into errors
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    unnecessary_const: error
    avoid_print: warning  # Start as warning, change to error later

  # Language strictness for type safety
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Exclude generated files
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - 'build/**'

linter:
  rules:
    # Good practices
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_returning_null
    - avoid_types_as_parameter_names
    - await_only_futures
    - curly_braces_in_flow_control_structures
    - empty_statements
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - use_setters_to_change_properties